#!/bin/bash


# Colors
GREEN='\033[1;32m' # Green
BLUE='\033[1;34m' # Blue
RED='\033[1;31m' # Red
RESET='\033[0m' # No Color



# Get Project Name
read -ep "Project name to re-import changes (site-name): " SLUG
[[ -z "$SLUG" ]] && exit || sleep 0


if [[ ! -d $SLUG ]]; then

	echo "There is no such project."
	exit

fi



# DETECT DB CHANGES
DB_FILE=$SLUG/database/dump/wordpress_data.sql
DB_SUM1=$(md5sum $DB_FILE)



# Pulling latest changes from git
(
	cd $SLUG/
	echo "Checking the latest remote changes..."
	git pull
	git reset --hard
	git clean -df wp/wp-content/
	git pull
	echo -e "Git pull complete ... ${GREEN}done${RESET}"
)




# Get environmental data
source $SLUG/.env



# Get current DB info
DBNAME=$(wp --path=$SLUG/wp config get DB_NAME)
DBUSER=$(wp --path=$SLUG/wp config get DB_USER)
DBPASS=$(wp --path=$SLUG/wp config get DB_PASSWORD)

export MYSQL_PWD=$DBPASS


# TEST THE DB
RESULT=`mysqlshow --user=${DBUSER} ${DBNAME}| grep -v Wildcard | grep -o ${DBNAME}`
if [ "$RESULT" != ${DBNAME} ]; then
    echo -e "${RED}Cannot connect to the DB.${RESET}"
    exit
fi



# DETECT DB CHANGES
DB_SUM2=$(md5sum $DB_FILE)
if [[ $DB_SUM1 != $DB_SUM2 ]]; then



	echo "DB changed."



	# Empty the DB
	echo -e "Cleaning the tables..."
	bash drop-mysql-tables.sh ${DBUSER} ${DBPASS} ${DBNAME}
	echo -e "All the tables removed ... ${GREEN}done${RESET}"



	# Import the new DB
	echo -e "DB importing..."
	mysql --silent --user=${DBUSER} ${DBNAME} < ${SLUG}/database/dump/wordpress_data.sql
	echo -e "DB imported ... ${GREEN}done${RESET}"



	# URL Replacement
	echo -e "DB url replacement starting..."
	wp --path=${SLUG}/wp search-replace "${DOMAIN}" "${PREFIX}.twelve12.co" --recurse-objects --report-changed-only --skip-columns=guid --skip-tables=wp_users --all-tables
	echo -e "DB url replacement finished ... ${GREEN}done${RESET}"



	# Rewrite Flush
	wp --path=${SLUG}/wp rewrite flush --hard



else


	echo "DB is identical."


fi




# PRINT THE SITE INFO
echo ""
echo ""
echo -e "== ${GREEN}Site Re-import Complete${RESET} ===================="
echo ""
echo "Live URL: http://${PREFIX}.twelve12.co"
echo ""
echo "================================="
echo ""
echo ""